blank_issues_enabled: false
contact_links:
  - name: Community Support
    url: https://github.com/4Source/settings-profiles-obsidian-plugin/discussions/new/choose
    about: Please ask and answer questions here.
